- name: 1-1 如果 /data/update 不存在则创建
  file:
    path: /data/update
    state: directory
    mode: '0755'

- name: 1-2 删除已有的 install.tar.gz
  file:
     path: /data/update/install.tar.gz
     state: absent

- name: 1-3 添加解压包
  archive:
    format: gz
    path:
      - "/data/server{{ area_id }}/game/p8_app_server"
      - "/data/server{{ area_id }}/game/server.sh"
      - "/data/server{{ area_id }}/game/proto"
      - "/data/server{{ area_id }}/game/etc"
      - "/data/server{{ area_id }}/game/lua"
    dest: /data/update/install.tar.gz
    mode: '0644'

- name: 1-4 发送到ansible中
  fetch:
    src: /data/update/install.tar.gz
    dest: "{{ playbook_dir }}/roles/game/files/install.tar.gz"
    flat: yes